### ISSUE TITLE
Where to get tokenizer.model

### ISSUE THREAD

**Issue by mycfhs** [allenai/unified-io-2.pytorch#13]
Hello! I failed to get tokenizer.model of meta llama model, and I use tokenizer.model in https://huggingface.co/allenai/tulu-v1-llama2-7b/tree/main instead. Could it be replaced? Or could you provide detailed path to tokenizer model?

**Comment by URRealHero** [comment]
Same problem!
When using 3.2's tokenizer from huggingface:
```python
/home/ls/miniforge3/envs/UnifiedIO2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/ls/miniforge3/envs/UnifiedIO2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
2024-12-06 22:21:57.203248: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-06 22:21:57.216241: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733494917.230907 1412919 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1733494917.235321 1412919 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-06 22:21:57.251409: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/ls/miniforge3/envs/UnifiedIO2/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
I0000 00:00:1733494996.054983 1412919 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79078 MB memory:  -> device: 0, name: NVIDIA A800 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
Traceback (most recent call last):
  File "/media/sata2/ps/mllm_as_a_judge++/Inference/VisualAudio2Text/UnifiedIO2_Inference.py", line 90, in <module>
    batch = preprocessor(
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/preprocessing.py", line 306, in __call__
    features = self.unified_io_preprocessor(features)
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/preprocessing.py", line 312, in unified_io_preprocessor
    fe = v.preprocess_inputs(features, self.tokenizer, self.sequence_length)
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/input_modalities.py", line 93, in preprocess_inputs
    text_inputs = tf.convert_to_tensor(vocab.encode(text_inputs))
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/vocabulary.py", line 318, in encode
    return self._encode(s)
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/vocabulary.py", line 303, in _encode
    return self.tokenizer.EncodeAsIds(s)
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/vocabulary.py", line 292, in tokenizer
    return self._model_context().tokenizer
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/vocabulary.py", line 120, in _model_context
    self._model = self._load_model(
  File "/media/sata2/ps/mllm_as_a_judge++/ModelDeploy/Any2Any/unified-io-2.pytorch/uio2/vocabulary.py", line 152, in _load_model
    model = sentencepiece_model_pb2.ModelProto.FromString(sp_model)
google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'
```

**Comment by mycfhs** [comment]
I haven't had any problems using this so far:  https://huggingface.co/allenai/tulu-v1-llama2-7b/tree/main

**Comment by URRealHero** [comment]
> I haven't had any problems using this so far: https://huggingface.co/allenai/tulu-v1-llama2-7b/tree/main

Get that, using tokenizer.model's path right?
btw, is the requirements.txt or requirements-exact.txt the correct env to use

**Comment by mycfhs** [comment]
I download "tokenizer.model" form here and put it to workspace with tokenizer="./tokenizer.model".
![6188b7b3-65a9-4a00-9627-ba85175e13e5](https://github.com/user-attachments/assets/b0414d46-87cb-47c5-9b2c-019db9f4c11c)

I only reinstall following package with env create on requirements.txt:
```
# python=3.10
pip install numpy==1.24.3   # ver 1.x
pip install tensorflow-gpu==2.8.0
```

**Comment by a5218522** [comment]
@mycfhs 感谢！

**Comment by URRealHero** [comment]
Thanks a lot~
